// src/renderer/pages/customers/modals/CustomerDetailDialog.tsx
import { Descriptions, Drawer, Tag } from 'antd';
import type { Customer } from '@shared/contracts/types';

const STATUS_TEXT: Record<string, string> = { active: '启用', inactive: '停用' };

export function CustomerDetailDialog({
  open,
  customer,
  onClose,
  onEdit,
}: {
  open: boolean;
  customer: Customer | null;
  onClose: () => void;
  onEdit: (c: Customer) => void;
}) {
  return (
    <Drawer
      title="客户详情"
      width={520}
      open={open}
      onClose={onClose}
      extra={customer && <a onClick={() => onEdit(customer)}>编辑</a>}
    >
      {customer && (
        <Descriptions column={1} bordered size="small">
          <Descriptions.Item label="客户名称">{customer.name}</Descriptions.Item>
          <Descriptions.Item label="客户编码">{customer.shortCode || '-'}</Descriptions.Item>
          <Descriptions.Item label="税号">{customer.taxId || '-'}</Descriptions.Item>
          <Descriptions.Item label="地址">{customer.address || '-'}</Descriptions.Item>
          <Descriptions.Item label="电话">{customer.phone || '-'}</Descriptions.Item>
          <Descriptions.Item label="开户行">{customer.bankName || '-'}</Descriptions.Item>
          <Descriptions.Item label="银行账号">{customer.bankAccount || '-'}</Descriptions.Item>
          <Descriptions.Item label="状态">
            <Tag color={customer.status === 'active' ? 'success' : 'default'}>
              {STATUS_TEXT[customer.status] ?? customer.status}
            </Tag>
          </Descriptions.Item>
          <Descriptions.Item label="创建时间">{customer.createdAt || '-'}</Descriptions.Item>
          <Descriptions.Item label="更新时间">{customer.updatedAt || '-'}</Descriptions.Item>
        </Descriptions>
      )}
    </Drawer>
  );
}

// src/renderer/pages/customers/modals/CustomerDetailDialog.vue
<template>
  <ElDialog :model-value="visible" title="客户详情" width="760px" @close="$emit('close')">
    <div v-if="customer" class="detail-content">
      <ElDescriptions :column="2" border>
        <ElDescriptionsItem label="客户名称">{{ customer.name }}</ElDescriptionsItem>
        <ElDescriptionsItem label="纳税人识别号">{{ customer.taxId }}</ElDescriptionsItem>
        <ElDescriptionsItem label="简码">{{ customer.shortCode || '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="地址">{{ customer.address || '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="电话">{{ customer.phone || '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="开户行">{{ customer.bankName || '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="银行账号">{{ customer.bankAccount || '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="邮箱">{{ customer.email || '-' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="默认地址">{{ customer.isDefaultAddress ? '是' : '否' }}</ElDescriptionsItem>
        <ElDescriptionsItem label="状态">
          <ElTag :type="customer.status === 'active' ? 'success' : 'danger'" size="small">
            {{ customer.status === 'active' ? '启用' : '停用' }}
          </ElTag>
        </ElDescriptionsItem>
        <ElDescriptionsItem label="最近更新">{{ formatTime(customer.updatedAt) }}</ElDescriptionsItem>
      </ElDescriptions>
    </div>
    <template #footer>
      <ElButton @click="$emit('close')">关闭</ElButton>
    </template>
  </ElDialog>
</template>

<script setup lang="ts">
import type { Customer } from '@shared/contracts/types';

defineProps<{
  visible: boolean;
  customer: Customer | null;
}>();

defineEmits<{ close: [] }>();

function formatTime(iso: string): string {
  try {
    return new Date(iso).toLocaleString('zh-CN');
  } catch {
    return iso;
  }
}
</script>
