// src/renderer/pages/outbound-records/components/OutboundRecordsTable.vue
<template>
  <div class="table-container">
    <ElTable :data="rows" v-loading="loading" border stripe size="default" :max-height="550" @row-click="handleRowClick">
      <ElTableColumn prop="batchNo" label="开票批次号" width="220" show-overflow-tooltip />
      <ElTableColumn label="客户名称" min-width="150">
        <template #default="{ row }">{{ row.customerSnapshot?.name || '-' }}</template>
      </ElTableColumn>
      <ElTableColumn prop="exportedAt" label="Excel 导出时间" width="170">
        <template #default="{ row }">{{ formatTime(row.exportedAt) }}</template>
      </ElTableColumn>
      <ElTableColumn prop="status" label="状态" width="90" align="center">
        <template #default="{ row }">
          <ElTag :type="row.status === 'valid' ? 'success' : 'danger'" size="small">
            {{ row.status === 'valid' ? '有效' : '已作废' }}
          </ElTag>
        </template>
      </ElTableColumn>
      <ElTableColumn prop="lineCount" label="明细行数" width="100" align="center" />
      <ElTableColumn prop="totalQuantity" label="数量合计" width="100" align="center" />
      <ElTableColumn label="金额" width="120">
        <template #default="{ row }">{{ centToDisplay(row.totalAmountCent) }}</template>
      </ElTableColumn>
      <ElTableColumn label="税额" width="120">
        <template #default="{ row }">{{ centToDisplay(row.totalTaxCent) }}</template>
      </ElTableColumn>
      <ElTableColumn label="价税合计" width="130">
        <template #default="{ row }">{{ centToDisplay(row.totalCent) }}</template>
      </ElTableColumn>
      <ElTableColumn label="操作" width="200" fixed="right">
        <template #default="{ row }">
          <ElButton link type="primary" size="small" @click.stop="$emit('viewDetail', row)">查看明细</ElButton>
          <ElButton link type="info" size="small" @click.stop="$emit('download', row)">下载</ElButton>
          <ElButton v-if="row.status === 'valid'" link type="danger" size="small" @click.stop="$emit('void', row)">作废</ElButton>
        </template>
      </ElTableColumn>
    </ElTable>
    <div class="pagination-container">
      <ElPagination
        v-model:current-page="currentPage"
        v-model:page-size="currentPageSize"
        :total="total"
        :page-sizes="[20, 50, 100]"
        layout="total, sizes, prev, pager, next, jumper"
        @current-change="$emit('pageChange', $event)"
        @size-change="$emit('sizeChange', $event)"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { centToDisplay } from '@shared/money';
import type { OutboundBatch } from '@shared/contracts/types';

const props = defineProps<{
  rows: OutboundBatch[];
  loading: boolean;
  page: number;
  pageSize: number;
  total: number;
}>();

const emit = defineEmits<{
  viewDetail: [row: OutboundBatch];
  download: [row: OutboundBatch];
  void: [row: OutboundBatch];
  pageChange: [page: number];
  sizeChange: [size: number];
}>();

const currentPage = computed({ get: () => props.page, set: () => {} });
const currentPageSize = computed({ get: () => props.pageSize, set: () => {} });

function handleRowClick(row: OutboundBatch): void {
  emit('viewDetail', row);
}

function formatTime(iso: string): string {
  try { return new Date(iso).toLocaleString('zh-CN'); } catch { return iso; }
}
</script>

// src/renderer/pages/outbound-records/components/OutboundRecordsTable.tsx
import type { ColumnsType } from 'antd/es/table';
import { Tag } from 'antd';
import type { OutboundBatch } from '@shared/contracts/types';
import { SharedTable } from '@renderer/components/SharedTable';
import { centToDisplay } from '@renderer/money';

function formatTime(iso: string): string {
  try {
    return new Date(iso).toLocaleString('zh-CN');
  } catch {
    return iso;
  }
}

export function OutboundRecordsTable({
  rows,
  loading,
  page,
  pageSize,
  total,
  onViewDetail,
  onDownload,
  onVoid,
  onRowClick,
  onPageChange,
  onSizeChange,
}: {
  rows: OutboundBatch[];
  loading: boolean;
  page: number;
  pageSize: number;
  total: number;
  onViewDetail: (row: OutboundBatch) => void;
  onDownload: (row: OutboundBatch) => void;
  onVoid: (row: OutboundBatch) => void;
  onRowClick: (row: OutboundBatch) => void;
  onPageChange: (page: number) => void;
  onSizeChange: (size: number) => void;
}) {
  const columns: ColumnsType<OutboundBatch> = [
    { title: '开票批次号', dataIndex: 'batchNo', width: 220, ellipsis: true },
    {
      title: '客户名称',
      minWidth: 150,
      render: (_, row) => row.customerSnapshot?.name || '-',
    },
    {
      title: 'Excel 导出时间',
      dataIndex: 'exportedAt',
      width: 170,
      render: (v: string) => formatTime(v),
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 90,
      align: 'center',
      render: (v: string) => (
        <Tag color={v === 'valid' ? 'success' : 'error'}>
          {v === 'valid' ? '有效' : '已作废'}
        </Tag>
      ),
    },
    { title: '明细行数', dataIndex: 'lineCount', width: 100, align: 'center' },
    { title: '数量合计', dataIndex: 'totalQuantity', width: 100, align: 'center' },
    { title: '金额', dataIndex: 'totalAmountCent', width: 120, render: (v: number) => centToDisplay(v) },
    { title: '税额', dataIndex: 'totalTaxCent', width: 120, render: (v: number) => centToDisplay(v) },
    { title: '价税合计', dataIndex: 'totalCent', width: 130, render: (v: number) => centToDisplay(v) },
    {
      title: '操作',
      width: 200,
      fixed: 'right',
      render: (_, row) => (
        <span className="flex gap-2">
          <a onClick={(e) => { e.stopPropagation(); onViewDetail(row); }}>查看明细</a>
          <a onClick={(e) => { e.stopPropagation(); onDownload(row); }}>下载</a>
          {row.status === 'valid' && (
            <a onClick={(e) => { e.stopPropagation(); onVoid(row); }}>作废</a>
          )}
        </span>
      ),
    },
  ];

  return (
    <SharedTable<OutboundBatch>
      rowKey="id"
      columns={columns}
      dataSource={rows}
      loading={loading}
      page={page}
      pageSize={pageSize}
      total={total}
      onRowClick={onRowClick}
      onPageChange={onPageChange}
      onSizeChange={onSizeChange}
    />
  );
}
