// src/renderer/pages/inventory/components/InventoryToolbar.tsx
import { Input, Select, Button, Space } from 'antd';
import {
  PlusOutlined,
  UploadOutlined,
  DownloadOutlined,
  ImportOutlined,
} from '@renderer/icons';
import { useAppStore } from '@renderer/stores/app';

export function InventoryToolbar({
  name,
  model,
  stockStatus,
  onNameChange,
  onModelChange,
  onStockStatusChange,
  onSearch,
  onReset,
  onRefresh,
  onAddProduct,
  onDailyImport,
  onOutbound,
  onMonthEndExport,
  onMonthBeginningImport,
  onInitialImport,
}: {
  name: string;
  model: string;
  stockStatus: string;
  onNameChange: (v: string) => void;
  onModelChange: (v: string) => void;
  onStockStatusChange: (v: string) => void;
  onSearch: () => void;
  onReset: () => void;
  onRefresh: () => void;
  onAddProduct: () => void;
  onDailyImport: () => void;
  onOutbound: () => void;
  onMonthEndExport: () => void;
  onMonthBeginningImport: () => void;
  onInitialImport: () => void;
}) {
  const productImportDone = useAppStore((s) => s.productImportDone);

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center gap-2 flex-wrap p-3 px-4 bg-white border border-line rounded-lg">
        <Input
          value={name}
          placeholder="项目名称"
          allowClear
          className="!w-[200px]"
          onChange={(e) => onNameChange(e.target.value)}
          onPressEnter={onSearch}
        />
        <Input
          value={model}
          placeholder="型号"
          allowClear
          className="!w-[160px]"
          onChange={(e) => onModelChange(e.target.value)}
          onPressEnter={onSearch}
        />
        <Select
          value={stockStatus}
          placeholder="库存状态"
          className="!w-[110px]"
          onChange={onStockStatusChange}
          options={[
            { label: '全部', value: 'all' },
            { label: '有余量', value: 'positive' },
            { label: '已平衡', value: 'zero' },
            { label: '待补票', value: 'negative' },
          ]}
        />
        <Button type="primary" onClick={onSearch}>
          搜索
        </Button>
        <Button onClick={onReset}>重置</Button>
        <Button className="!ml-auto" onClick={onRefresh}>
          刷新
        </Button>
      </div>

      <div className="flex flex-wrap gap-3">
        <div className="bg-white border border-line rounded-lg p-4 flex-1 min-w-[280px]">
          <div className="text-sm font-medium text-gray-700 mb-3">库存与开票</div>
          <Space wrap>
            <Button type="primary" onClick={onOutbound}>
              销项开票
            </Button>
            <Button onClick={onMonthEndExport} icon={<DownloadOutlined />}>
              导出补票清单
            </Button>
            <Button onClick={onMonthBeginningImport} icon={<ImportOutlined />}>
              月初进项
            </Button>
          </Space>
        </div>

        <div className="bg-white border border-line rounded-lg p-4 flex-1 min-w-[280px]">
          <div className="text-sm font-medium text-gray-700 mb-3">商品管理</div>
          <Space wrap>
            <Button icon={<PlusOutlined />} onClick={onAddProduct}>
              新增商品
            </Button>
            <Button icon={<UploadOutlined />} onClick={onDailyImport}>
              商品导入
            </Button>
            {!productImportDone && (
              <Button danger onClick={onInitialImport}>
                初始化导入
              </Button>
            )}
          </Space>
        </div>
      </div>
    </div>
  );
}

// src/renderer/pages/inventory/components/InventoryToolbar.vue
<template>
  <div class="inventory-toolbar">
    <!-- 筛选行 -->
    <div class="toolbar-filters">
      <ElInput
        :model-value="name"
        placeholder="项目名称"
        clearable
        style="width: 200px"
        @update:model-value="$emit('update:name', $event)"
        @keyup.enter="$emit('search')"
      />
      <ElInput
        :model-value="model"
        placeholder="型号"
        clearable
        style="width: 160px"
        @update:model-value="$emit('update:model', $event)"
        @keyup.enter="$emit('search')"
      />
      <ElSelect :model-value="stockStatus" placeholder="库存状态" style="width: 110px" @update:model-value="$emit('update:stockStatus', $event)">
        <ElOption label="全部" value="all" />
        <ElOption label="有余量" value="positive" />
        <ElOption label="已平衡" value="zero" />
        <ElOption label="待补票" value="negative" />
      </ElSelect>
      <ElButton type="primary" @click="$emit('search')">搜索</ElButton>
      <ElButton @click="$emit('reset')">重置</ElButton>
      <ElButton style="margin-left: auto" @click="$emit('refresh')">刷新</ElButton>
    </div>

    <!-- 操作按钮行 - 三列布局，记录与工具靠右 -->
    <div class="toolbar-actions">
      <div class="action-col">
        <div class="action-col-title">商品管理</div>
        <div class="action-col-btns">
          <ElButton type="success" @click="$emit('add-product')">
            <ElIcon><Plus /></ElIcon>新增商品
          </ElButton>
          <ElButton @click="$emit('daily-import')">
            <ElIcon><Upload /></ElIcon>商品导入
          </ElButton>
        </div>
      </div>
      <div class="action-col">
        <div class="action-col-title">库存与开票</div>
        <div class="action-col-btns">
          <ElButton type="primary" @click="$emit('outbound')">
            <ElIcon><Ticket /></ElIcon>销项开票
          </ElButton>
          <ElButton type="warning" @click="$emit('month-end-export')">
            <ElIcon><Download /></ElIcon>月底导出
          </ElButton>
          <ElButton type="info" @click="$emit('month-beginning-import')">
            <ElIcon><Upload /></ElIcon>月初进项
          </ElButton>
        </div>
      </div>
      <div class="action-col action-col-right">
        <div class="action-col-title">记录与工具</div>
        <div class="action-col-btns">
          <ElButton @click="$emit('import-records')">
            <ElIcon><List /></ElIcon>导入记录
          </ElButton>
          <ElButton @click="$emit('view-history')">
            <ElIcon><Notebook /></ElIcon>历史记录
          </ElButton>
          <ElButton
            v-if="!appStore.productImportDone"
            type="danger"
            @click="$emit('initial-import')"
          >
            <ElIcon><WarningFilled /></ElIcon>初始化导入
          </ElButton>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useAppStore } from '../../../stores/app';

defineProps<{
  name: string;
  model: string;
  stockStatus: string;
}>();

defineEmits<{
  'update:name': [val: string];
  'update:model': [val: string];
  'update:stockStatus': [val: string];
  search: [];
  reset: [];
  refresh: [];
  outbound: [];
  'add-product': [];
  'initial-import': [];
  'daily-import': [];
  'month-end-export': [];
  'month-beginning-import': [];
  'import-records': [];
  'view-history': [];
}>();

const appStore = useAppStore();
</script>

<style scoped>
.inventory-toolbar {
  margin-bottom: 12px;
}

.toolbar-filters {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
  margin-bottom: 12px;
  padding: 12px 16px;
  background: var(--card-bg);
  border: 1px solid var(--card-border);
  border-radius: var(--card-radius);
}

.toolbar-actions {
  display: flex;
  gap: 16px;
  padding: 14px 16px;
  background: var(--card-bg);
  border: 1px solid var(--card-border);
  border-radius: var(--card-radius);
}

.action-col {
  min-width: 0;
}

.action-col-right {
  margin-left: auto;
}

.action-col-title {
  font-size: 12px;
  color: var(--text-secondary);
  margin-bottom: 8px;
  font-weight: 500;
}

.action-col-btns {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}
</style>
