// src/renderer/pages/inventory/modals/OutboundExportDialog.vue
<template>
  <ElDialog
    v-model="dialogVisible"
    title="销项开票"
    width="90vw"
    top="5vh"
    :close-on-click-modal="false"
    destroy-on-close
    @close="handleClose"
  >
    <div class="outbound-content">
      <!-- 客户选择 -->
      <ElForm :inline="true" class="customer-form">
        <ElFormItem label="开票客户" required>
          <ElSelect
            v-model="selectedCustomerId"
            filterable
            remote
            :remote-method="searchCustomers"
            :loading="customerLoading"
            placeholder="选择启用客户"
            style="width: 300px"
          >
            <ElOption v-for="c in customerOptions" :key="c.id" :label="`${c.name} (${c.taxId})`" :value="c.id" />
          </ElSelect>
        </ElFormItem>
        <ElFormItem label="金额系数">
          <ElInput
            v-model="amountFactor"
            style="width: 120px"
            placeholder="1.09"
            @change="handleFactorChange"
          />
        </ElFormItem>
      </ElForm>

      <!-- 商品明细和汇总 -->
      <OutboundLineTable :lines="lines" :factor="amountFactor" @change="recalculate" @remove="removeLine" />
    </div>

    <template #footer>
      <ElButton @click="handleClose">取消</ElButton>
      <ElButton type="primary" :loading="exporting" :disabled="!selectedCustomerId || lines.length === 0" @click="handleExport">
        确认导出
      </ElButton>
    </template>
  </ElDialog>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { api } from '../../../api';
import { useSelectionStore } from '../../../stores/selection';
import type { SelectedPriceVersion } from '../../../stores/selection';
import type { Customer } from '@shared/contracts/types';
import type { DraftValidationResult } from '@shared/contracts/preview-types';
import type { OutboundExportInput } from '@shared/schemas';
import { calcOutboundAmountCent, centToYuan, yuanToCent } from '@shared/money';
import OutboundLineTable from './OutboundLineTable.vue';

const props = defineProps<{ visible: boolean; initialLines: SelectedPriceVersion[] }>();
const emit = defineEmits<{ close: []; success: [] }>();

const dialogVisible = computed({ get: () => props.visible, set: () => emit('close') });
const selectionStore = useSelectionStore();
const selectedCustomerId = ref('');
const customerOptions = ref<Customer[]>([]);
const customerLoading = ref(false);
const exporting = ref(false);
const amountFactor = ref('1.09');

interface OutboundLine {
  priceVersionId: string; name: string; model: string; unit: string;
  unitPriceDecimal: string; stockBalance: number; quantity: number; amountYuan: string;
}
const lines = reactive<OutboundLine[]>([]);

watch(() => props.visible, (val) => {
  if (val) {
    lines.length = 0;
    for (const item of props.initialLines) {
      const pv = item.row;
      lines.push({
        priceVersionId: pv.priceVersionId, name: pv.name, model: pv.model, unit: pv.unit,
        unitPriceDecimal: pv.unitPriceDecimal, stockBalance: pv.stockBalance, quantity: item.quantity,
        amountYuan: centToYuan(calcOutboundAmountCent(item.quantity, pv.unitPriceDecimal, amountFactor.value)),
      });
    }
    loadCustomers();
  }
}, { immediate: true });

async function loadCustomers(): Promise<void> {
  customerLoading.value = true;
  try {
    const result = await api.customers.list({ page: 1, pageSize: 100, status: 'active' });
    customerOptions.value = result.rows;
  } finally {
    customerLoading.value = false;
  }
}

async function searchCustomers(query: string): Promise<void> {
  customerLoading.value = true;
  try {
    const result = await api.customers.list({ page: 1, pageSize: 100, keyword: query, status: 'active' });
    customerOptions.value = result.rows;
  } finally {
    customerLoading.value = false;
  }
}

function removeLine(index: number): void {
  lines.splice(index, 1);
}

function recalculate(): void {
  // 触发响应式重算（子组件内 computed 自动更新）
}

/** 统一系数变化时重新计算弹窗内全部行金额。 */
function handleFactorChange(): void {
  try {
    for (const line of lines) {
      line.amountYuan = centToYuan(
        calcOutboundAmountCent(line.quantity, line.unitPriceDecimal, amountFactor.value),
      );
    }
  } catch {
    amountFactor.value = '1.09';
    for (const line of lines) {
      line.amountYuan = centToYuan(calcOutboundAmountCent(line.quantity, line.unitPriceDecimal, '1.09'));
    }
    ElMessage.warning('金额系数无效，已恢复为 1.09');
  }
}

/** 将弹窗中的金额字符串转换为后端使用的整数分。 */
function parseLineAmountCent(line: OutboundLine): number {
  const amountCent = yuanToCent(line.amountYuan);
  if (amountCent <= 0) throw new Error(`“${line.name}”的金额必须大于 0`);
  return amountCent;
}

async function handleExport(): Promise<void> {
  if (lines.length > 2000) {
    ElMessage.error('单次最多 2000 条明细');
    return;
  }
  try {
    exporting.value = true;
    const input: OutboundExportInput = {
      customerId: selectedCustomerId.value,
      lines: lines.map((l) => ({
        priceVersionId: l.priceVersionId,
        quantity: l.quantity,
        amountCent: parseLineAmountCent(l),
      })),
      amountFactor: amountFactor.value,
    };

    const draft: DraftValidationResult = await api.outbound.validateDraft(input);
    if (draft.invalidPriceVersionIds.length > 0) {
      selectionStore.removeInvalid(draft.invalidPriceVersionIds);
      ElMessage.warning(`部分价格版本已失效并从已选中移除：${draft.errors.join('; ')}`);
      if (draft.validLines.length === 0) { exporting.value = false; return; }
      input.lines = draft.validLines.map((l) => ({
        priceVersionId: l.priceVersionId,
        quantity: l.quantity,
        amountCent: l.amountCent,
      }));
    }

    const result = await api.outbound.export(input);
    if (result.saved) {
      ElMessage.success(`导出成功，批次号: ${result.batchNo}`);
      selectionStore.clearSelection();
      emit('success');
    } else {
      ElMessage.warning('导出已取消');
    }
  } catch (err) {
    ElMessage.error(`导出失败: ${(err as Error).message}`);
  } finally {
    exporting.value = false;
  }
}

function handleClose(): void {
  emit('close');
}
</script>

<style scoped>
.outbound-content {
  display: flex;
  flex-direction: column;
  gap: 16px;
}
</style>

// src/renderer/pages/inventory/modals/OutboundExportDialog.tsx
import { useEffect, useState } from 'react';
import { Button, Checkbox, Input, Modal, Select, Space, Typography, App } from 'antd';
import type { Customer } from '@shared/contracts/types';
import type { DraftValidationResult } from '@shared/contracts/preview-types';
import Decimal from 'decimal.js';
import {
  centToDisplay,
  centToYuan,
  OUTBOUND_AMOUNT_FACTOR,
  roundUnitPriceToWholeYuan,
  scaleUnitPrice,
  yuanToCent,
} from '@shared/money';
import { api } from '@renderer/api';
import { useSelectionStore } from '@renderer/stores/selection';
import { OutboundLinesTable } from './OutboundLinesTable';

const { Text } = Typography;

export interface OutboundLine {
  productId: string;
  name: string;
  model: string;
  unit: string;
  unitPriceDecimal: string;
  stockBalance: number;
  quantity: number;
  /** 税利单价 = 含税单价 × 1.09（勾选时四舍五入到整数元） */
  scaledUnitPriceDecimal: string;
  /** 当前商品总价（元）= 税利单价 × 数量 */
  amountYuan: string;
}

/** 由含税单价、数量、是否自动四舍五入、系数，重算税利单价与当前商品总价。 */
function recompute(
  unitPrice: string,
  qty: number,
  autoRound: boolean,
  factor: string,
): { scaledUnitPriceDecimal: string; amountYuan: string } {
  const scaled = autoRound
    ? roundUnitPriceToWholeYuan(scaleUnitPrice(unitPrice, factor))
    : scaleUnitPrice(unitPrice, factor);
  const totalCent = new Decimal(scaled).times(qty).times(100).toDecimalPlaces(0, Decimal.ROUND_HALF_UP).toNumber();
  return { scaledUnitPriceDecimal: scaled, amountYuan: centToYuan(totalCent) };
}

export function OutboundExportDialog({
  open,
  onClose,
  onExported,
}: {
  open: boolean;
  onClose: () => void;
  onExported: () => void;
}) {
  const { message } = App.useApp();
  const selectionStore = useSelectionStore();

  const [customers, setCustomers] = useState<Customer[]>([]);
  const [customerId, setCustomerId] = useState<string | undefined>();
  const [customerLoading, setCustomerLoading] = useState(false);
  const [amountFactor, setAmountFactor] = useState(OUTBOUND_AMOUNT_FACTOR);
  const [autoRound, setAutoRound] = useState(true);
  const [lines, setLines] = useState<OutboundLine[]>([]);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!open) return;
    setCustomerId(undefined);
    setAmountFactor(OUTBOUND_AMOUNT_FACTOR);
    setAutoRound(true);
    loadCustomers();

    const selected: OutboundLine[] = selectionStore.selections
      .filter((sel) => sel.valid)
      .map((sel) => {
        const meta = sel.meta as Record<string, unknown>;
        const qty = selectionStore.getQuantity(sel.key);
        const unitPriceDecimal = String(meta.unitPriceDecimal ?? '0');
        const { scaledUnitPriceDecimal, amountYuan } = recompute(
          unitPriceDecimal,
          qty,
          true,
          OUTBOUND_AMOUNT_FACTOR,
        );
        return {
          productId: sel.key,
          name: (meta.name as string) ?? sel.label,
          model: (meta.model as string) ?? '',
          unit: (meta.unit as string) ?? '',
          unitPriceDecimal,
          stockBalance: Number(meta.stockBalance ?? 0),
          quantity: qty,
          scaledUnitPriceDecimal,
          amountYuan,
        };
      });
    setLines(selected);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open]);

  const loadCustomers = async (keyword?: string) => {
    setCustomerLoading(true);
    try {
      const res = await api.customers.list({
        status: 'active',
        page: 1,
        pageSize: 100,
        keyword: keyword?.trim() || undefined,
      });
      setCustomers(res.rows);
    } catch {
      setCustomers([]);
    } finally {
      setCustomerLoading(false);
    }
  };

  const updateQty = (id: string, qty: number) => {
    setLines((prev) =>
      prev.map((l) =>
        l.productId === id
          ? { ...l, quantity: qty, ...recompute(l.unitPriceDecimal, qty, autoRound, amountFactor) }
          : l,
      ),
    );
  };

  const removeLine = (id: string) => setLines((prev) => prev.filter((l) => l.productId !== id));

  const applyFactor = () => {
    setLines((prev) =>
      prev.map((l) => ({ ...l, ...recompute(l.unitPriceDecimal, l.quantity, autoRound, amountFactor) })),
    );
  };

  const toggleAutoRound = (checked: boolean) => {
    setAutoRound(checked);
    setLines((prev) =>
      prev.map((l) => ({ ...l, ...recompute(l.unitPriceDecimal, l.quantity, checked, amountFactor) })),
    );
  };

  const totalQuantity = lines.reduce((s, l) => s + (l.quantity > 0 ? l.quantity : 0), 0);
  const totalBaseCent = lines.reduce((s, l) => {
    try {
      return s + new Decimal(l.unitPriceDecimal).times(l.quantity).times(100).toDecimalPlaces(0, Decimal.ROUND_HALF_UP).toNumber();
    } catch {
      return s;
    }
  }, 0);
  const totalAmountCent = lines.reduce((s, l) => {
    try {
      return s + yuanToCent(l.amountYuan);
    } catch {
      return s;
    }
  }, 0);
  const totalProfitCent = totalAmountCent - totalBaseCent;

  const canExport = !!customerId && lines.length > 0 && lines.every((l) => l.quantity > 0);

  const handleExport = async () => {
    if (!canExport || !customerId) {
      message.warning('请选择客户并填写每行的正整数数量');
      return;
    }
    if (lines.length > 2000) {
      message.error('单次最多 2000 条明细');
      return;
    }
    setBusy(true);
    try {
      const payload = {
        customerId,
        amountFactor,
        lines: lines.map((l) => ({
          productId: l.productId,
          quantity: l.quantity,
          amountCent: yuanToCent(l.amountYuan),
        })),
      };

      const draft = (await api.outbound.validateDraft(payload)) as DraftValidationResult;
      if (draft.invalidProductIds.length > 0) {
        selectionStore.removeInvalid(draft.invalidProductIds);
        setLines((prev) => prev.filter((l) => !draft.invalidProductIds.includes(l.productId)));
        message.warning(`部分商品已失效并移除：${draft.errors.join('；')}`);
        if (draft.validLines.length === 0) {
          setBusy(false);
          return;
        }
      }

      const res = (await api.outbound.export(payload)) as {
        saved: boolean;
        batchNo: string;
        path?: string;
      };
      if (res.saved) {
        message.success(`已导出：${res.batchNo}`);
        selectionStore.clear();
        onExported();
        onClose();
      } else {
        message.error('导出失败');
      }
    } catch (e) {
      message.error(`导出失败：${(e as Error).message}`);
    } finally {
      setBusy(false);
    }
  };

  return (
    <Modal
      title="销项开票"
      open={open}
      onCancel={onClose}
      width={1020}
      footer={
        <div className="flex items-center justify-between">
          <Space size="large">
            <Text className="!text-brand">商品种类 {lines.length}</Text>
            <Text className="!text-muted">数量合计 {totalQuantity}</Text>
            <Text className="!text-blue-500">含税总价 {centToDisplay(totalBaseCent)}</Text>
            <Text className="!text-green-600">利润 {centToDisplay(totalProfitCent)}</Text>
            <Text strong className="!text-red-500">全部总计 {centToDisplay(totalAmountCent)}</Text>
          </Space>
          <Space>
            <Button onClick={onClose}>取消</Button>
            <Button type="primary" loading={busy} disabled={!canExport} onClick={handleExport}>
              确认导出
            </Button>
          </Space>
        </div>
      }
    >
      <Space direction="vertical" size="middle" className="!w-full">
        <Space className="!w-full" wrap>
          <Select
            className="!w-[320px]"
            placeholder="选择开票客户（仅启用客户）"
            value={customerId}
            onChange={setCustomerId}
            loading={customerLoading}
            showSearch
            optionFilterProp="label"
            filterOption={false}
            onSearch={(v) => loadCustomers(v)}
            options={customers.map((c) => ({ value: c.id, label: `${c.name} (${c.taxId})` }))}
          />
          <Space>
            <Text type="secondary">金额系数</Text>
            <Input
              value={amountFactor}
              className="!w-[100px]"
              onChange={(e) => setAmountFactor(e.target.value)}
              onBlur={applyFactor}
            />
          </Space>
          <Checkbox checked={autoRound} onChange={(e) => toggleAutoRound(e.target.checked)}>
            含税单价 × 1.09 后自动四舍五入
          </Checkbox>
        </Space>

        <OutboundLinesTable
          lines={lines}
          autoRound={autoRound}
          onQuantityChange={updateQty}
          onRemove={removeLine}
        />
      </Space>
    </Modal>
  );
}
